runtime:
  cache_dir: ./.cache/antora

site:
  title: Quarkus from Zero to Serverless Guide
  url: https//atarazana.github.io/quarkus-zero-to-serverless-guide
  start_page: quarkus-zero-to-serverless-guide::index.adoc

content:
  sources:
    - url: git@github.com:atarazana/quarkus-zero-to-serverless-guide.git
      tags: []
      branches: [main]
      start_path: documentation

asciidoc:
  attributes:
    title: Quarkus from Zero to Serverless Guide
    release-version: main
    page-pagination: true
    git_base: https://github.com/atarazana
    git_uri: quarkus-zero-to-serverless-guide
    git_ref: main
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/redhat-scholars/course-ui/releases/download/v0.1.8/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
#    - path: ./supplemental-ui
#    - path: .nojekyll
#    - path: ui.yml
#      contents: "static_files: [ .nojekyll ]"

output:
  dir: ./gh-pages
