
= Deploying the Atomic Fruit Service on OpenShift
include::_attributes.adoc[]

[#deploying-to-openshift]
== Deploying to OpenShift

WARNING: Before proceeding you must be logged in to the OpenShift cluster. Also, yo have to be at `$CHE_PROJECTS_ROOT/quarkus-zero-to-serverless-guide/atomic-fruit-service` directory in all your terminals.

First of all let\'s add the extension to deploy to OpenShift.

[.console-input]
[source,sh,role="copypaste"]
----
cd ${CHE_PROJECTS_ROOT}/atomic-fruit-service
mvn quarkus:add-extension -Dextension="openshift"
----

Output:
[.console-output]
[source,console]
----
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------< com.redhat.atomic.fruit:atomic-fruit-service >------------
[INFO] Building atomic-fruit-service 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.9.2.Final:add-extension (default-cli) @ atomic-fruit-service ---
✅ Extension io.quarkus:quarkus-openshift has been installed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.200 s
[INFO] Finished at: 2021-03-31T18:27:06Z
[INFO] ------------------------------------------------------------------------
----

Add this couple of properties to `{artifact_id_quarkus}/src/main/resources/application.properties` so that we trust on the CA cert and set the namespace where we want to deploy our application.

[source,properties,subs="attributes+",role="copypaste"]
----
## Kubernetes Client
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes-client.namespace=${PROJECT_NAME:{project_name}}

## Only generate OpenShift descriptors
quarkus.kubernetes.deployment-target=openshift

## Expose the service when deployed
quarkus.openshift.expose=true
----

Let\'s add a some additional labels `part-of` and `name`, and a custom label:

[source,properties,subs="attributes+",role="copypaste"]
----
## Recommended labels and a custom label for kubernetes and openshift
quarkus.openshift.part-of={app_name}
quarkus.openshift.name={artifact_id_quarkus}
quarkus.openshift.labels.department=fruity-dept
----

Regarding annotations, out of the box, the generated resources will be annotated with version control related information that can be used either by tooling, or by the user for troubleshooting purposes.

[source,yaml]
----
annotations:
  app.quarkus.io/vcs-url: "<some url>"
  app.quarkus.io/commit-id: "<some git SHA>"
----

Let\'s add a custom annotation:

[source,properties,role="copypaste"]
----
## Custom annotations
quarkus.openshift.annotations."app.openshift.io/connects-to"=my-database
quarkus.openshift.annotations.foo=bar
quarkus.openshift.annotations."app.quarkus/id"=42
----

So far we haven\'t prepared the production profile, for instance we have no secret to keep the database credentials. Let\'s do something about it. Let\'s create a secret locally first.

NOTE: `openshift` extension takes the file we\'re generating and merge it with the one generated

[.console-input]
[source,sh,role="copypaste"]
----
mkdir -p $CHE_PROJECTS_ROOT/atomic-fruit-service/src/main/kubernetes && \
cat <<EOF > $CHE_PROJECTS_ROOT/atomic-fruit-service/src/main/kubernetes/openshift.yml
---
apiVersion: v1
kind: Secret
metadata:
  name: fruits-database-secret
stringData:
  user: luke
  password: secret
EOF
----

Now let\'s add the environment variables we need to connect to the database, replace database related properties with these:

[source,properties,role="copypaste",subs="attributes+"]
----
#################################
## BEGIN: Data Base related properties

## Environment variables
quarkus.openshift.env.mapping.db-username.from-secret=fruits-database-secret
quarkus.openshift.env.mapping.db-username.with-key=user
quarkus.openshift.env.mapping.db-password.from-secret=fruits-database-secret
quarkus.openshift.env.mapping.db-password.with-key=password

%prod.quarkus.datasource.jdbc.url = jdbc:postgresql://my-database.{project_name}:5432/my_data
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username = ${DB_USERNAME}
%prod.quarkus.datasource.password = ${DB_PASSWORD}

%dev.quarkus.datasource.jdbc.url = jdbc:h2:mem:myDB
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.username = username-default

%test.quarkus.datasource.jdbc.url = jdbc:h2:mem:myDB
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username = username-default

## drop and create the database at startup (use `update` to only update the schema)
%prod.quarkus.hibernate-orm.database.generation = create
quarkus.hibernate-orm.database.generation = drop-and-create
quarkus.hibernate-orm.sql-load-script = import.sql
## show sql statements in log
quarkus.hibernate-orm.log.sql = true

## END: Data Base related properties
#################################
----

Let\'s package our application and have a look to the descriptors generated.

[.console-input]
[source,sh,role="copypaste"]
----
mvn clean package -DskipTests
----


You can check the generated file `$CHE_PROJECTS_ROOT/atomic-fruit-service/target/kubernetes/openshift.yml`, there you\'ll find: Service and Deployment...

Let\'s deploy the result:

NOTE: We make sure the default project is `{project_name}`, this is necessary because the plugin used to deploy in OpenShift deploys in the default project unless indicated otherwise.

[.console-input]
[source,sh,role="copypaste",subs="attributes+"]
----
oc project {project_name} && \
mvn clean package -Dquarkus.kubernetes.deploy=true -DskipTests
----

[TIP]
====
The other, and equivalent, approach is to use the `oc` client instead of the maven script:

[.console-input]
[source,sh,subs="attributes+",role="copypaste"]
----
oc apply -n {project_name} -f $CHE_PROJECTS_ROOT/atomic-fruit-service/target/kubernetes/openshift.yml
----
====

Let\'s inspect the resources created.

[.console-input]
[source,sh,subs="attributes+",role="copypaste"]
----
oc get dc,deploy -n {project_name}
----

[.console-output]
[source,console]
----
NAME                                                      REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfig.apps.openshift.io/atomic-fruit-service   1          1         1         image(atomic-fruit-service:1.0-SNAPSHOT)

NAME                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/my-database   1/1     1            1           96m
----

Now we can test that everything works properly.

[.console-input]
[source,sh,role="copypaste"]
----
curl http://$(oc get route atomic-fruit-service -o jsonpath='{.spec.host}')/fruit
----

[#evolving-to-serverless]
== Evolving to Serverless
include::_attributes.adoc[]

In order to deploy our app to OpenShift as a Knative service... Let\'s add a new target platform. Find the next property and make sure its value is `openshift,knative` instead of just `openshift`.

[source,properties,role="copypaste"]
----
## Generate OpenShift and Knative descriptors
quarkus.kubernetes.deployment-target=openshift,knative
----

And this properties to tune the Knative deployment.

[source,properties,subs="attributes+",role="copypaste"]
----
## Knative
quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000
quarkus.container-image.group=${PROJECT_NAME:{project_name}}
quarkus.container-image.tag=1.0-SNAPSHOT
quarkus.knative.name={artifact_id_quarkus}-kn
quarkus.knative.version=1.0
quarkus.knative.part-of={app_name}
quarkus.knative.annotations."app.openshift.io/connects-to"=my-database
quarkus.knative.labels."app.openshift.io/runtime"=quarkus
quarkus.knative.env.mapping.db-username.from-secret=fruits-database-secret
quarkus.knative.env.mapping.db-username.with-key=user
quarkus.knative.env.mapping.db-password.from-secret=fruits-database-secret
quarkus.knative.env.mapping.db-password.with-key=password
----

Time to deploy using Knative.

[.console-input]
[source,sh,role="copypaste"]
----
cd ${CHE_PROJECTS_ROOT}/atomic-fruit-service
mvn clean package -DskipTests && \
oc apply -f target/kubernetes/knative.yml
----